services:
  prometheus:
    image: prom/prometheus
    container_name: "${PROJECT_NAME}-prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - 9090:9090
    restart: always


  grafana:
    image: grafana/grafana
    container_name: "${PROJECT_NAME}-grafana"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  loki:
    image: grafana/loki
    container_name: "${PROJECT_NAME}-loki"
    ports:
      - 3100:3100

volumes:
  prom_data:
