global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - 127.0.0.1:9090

- job_name: host-metrics
  static_configs:
  - targets:
    - 10.129.0.32:9100

- job_name: docker-metrics
  static_configs:
  - targets:
    - 10.129.0.32:8000
